name: Jazzy Docs

# Solo ejecutar cuando se cambia al main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Instalar Bundle
      run: bundle install
    - name: Corre pod install
      run: bundle exec fastlane cocoapodLane
    - name: Publish Jazzy Docs
      uses: steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        config: .jazzy.yaml